-- TODO TABLE
CREATE TABLE TODOS (
    ID NUMBER PRIMARY KEY,
    CONTENT VARCHAR2(200),
    IS_DONE NUMBER DEFAULT 0,
    CREATED_DATE DATE DEFAULT SYSDATE
);

-- EMOTION DIARY TABLE
CREATE TABLE EMOTION_DIARY (
    ID NUMBER PRIMARY KEY,
    CONTENT VARCHAR2(500),
    EMOTION VARCHAR2(50),
    CREATED_DATE DATE DEFAULT SYSDATE
);